### ISSUE TITLE
Fails to properly serialize Active Record descendants with unsaved records

### ISSUE THREAD

**Issue by cmer** [hopsoft/universalid#30]
```ruby
invoice = Enrollment::Invoice.last
puts invoice.items.length # equals 1

invoice.items << invoice.items.build
puts invoice.items.length # equals 2

options = {
    include_blank: true,
    include_unsaved_changes: true,
    include_descendants: true,
    descendant_depth: 2,
    include_keys: true
  }
str = URI::UID.build(invoice, options).to_s
new_invoice = URI::UID.parse(str).decode
puts new_invoice.items.length # should equal 2, but equals 1.  <-------------
```

**Comment by hopsoft** [comment]
Some additional detail: This is because `incldue_descendants` operates on loaded associations. We need to update the internals to ensure that persisted descendants are also included.

**Comment by hopsoft** [comment]
I decided to tackle this feature in the PR I'm current working on _(along with `marked_for_destruction` tracking)_. Here are the relevant commits for each.

- [Marked for destruction tracking](https://github.com/hopsoft/universalid/pull/29/commits/5d570aace14d4d3eb63076155ce05346baf4bfeb)
- [Unsaved descendant tracking](https://github.com/hopsoft/universalid/pull/29/commits/5d570aace14d4d3eb63076155ce05346baf4bfeb)
