### ISSUE TITLE
could we serialize blocks? 🤯

### ISSUE THREAD

**Issue by adrianthedev** [hopsoft/universalid#43]
This isn't a UniversalID question per-se, but looking at your experience, I wanted to pop the question.

Have you seen any cases of serializing a block?

I can dig into our use-case a bit more if that would help.

**Comment by hopsoft** [comment]
I've got another project that does this by reading the proc code and basically loading that code in another process. The challenge is that you have to pack up the binding as well.

**Comment by hopsoft** [comment]
Not sure this would be in the scope of the library, but when I get back to it I can share my other efforts for serializing blocks.
